/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedMarketRouteImport } from './routes/_authenticated.market'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated.orders'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated.portfolio'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated.wallet'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated.watchlist'
import { Route as PaymentFailureRouteImport } from './routes/payment.failure'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as AuthenticatedMarketSymbolRouteImport } from './routes/_authenticated.market.$symbol'
import { Route as AuthenticatedWalletIndexRouteImport } from './routes/_authenticated.wallet.index'
import { Route as AuthenticatedWalletDepositRouteImport } from './routes/_authenticated.wallet.deposit'
import { Route as AuthenticatedWalletHistoryRouteImport } from './routes/_authenticated.wallet.history'
import { Route as AuthenticatedWalletTransferRouteImport } from './routes/_authenticated.wallet.transfer'
import { Route as AuthenticatedWalletWithdrawRouteImport } from './routes/_authenticated.wallet.withdraw'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketRoute = AuthenticatedMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PaymentFailureRoute = PaymentFailureRouteImport.update({
  id: '/payment/failure',
  path: '/payment/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMarketSymbolRoute =
  AuthenticatedMarketSymbolRouteImport.update({
    id: '/$symbol',
    path: '/$symbol',
    getParentRoute: () => AuthenticatedMarketRoute,
  } as any)
const AuthenticatedWalletIndexRoute =
  AuthenticatedWalletIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWalletRoute,
  } as any)
const AuthenticatedWalletDepositRoute =
  AuthenticatedWalletDepositRouteImport.update({
    id: '/deposit',
    path: '/deposit',
    getParentRoute: () => AuthenticatedWalletRoute,
  } as any)
const AuthenticatedWalletHistoryRoute =
  AuthenticatedWalletHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedWalletRoute,
  } as any)
const AuthenticatedWalletTransferRoute =
  AuthenticatedWalletTransferRouteImport.update({
    id: '/transfer',
    path: '/transfer',
    getParentRoute: () => AuthenticatedWalletRoute,
  } as any)
const AuthenticatedWalletWithdrawRoute =
  AuthenticatedWalletWithdrawRouteImport.update({
    id: '/withdraw',
    path: '/withdraw',
    getParentRoute: () => AuthenticatedWalletRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/market': typeof AuthenticatedMarketRouteWithChildren
  '/orders': typeof AuthenticatedOrdersRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/wallet': typeof AuthenticatedWalletRouteWithChildren
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/payment/failure': typeof PaymentFailureRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/market/$symbol': typeof AuthenticatedMarketSymbolRoute
  '/wallet/deposit': typeof AuthenticatedWalletDepositRoute
  '/wallet/history': typeof AuthenticatedWalletHistoryRoute
  '/wallet/transfer': typeof AuthenticatedWalletTransferRoute
  '/wallet/withdraw': typeof AuthenticatedWalletWithdrawRoute
  '/wallet/': typeof AuthenticatedWalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/market': typeof AuthenticatedMarketRouteWithChildren
  '/orders': typeof AuthenticatedOrdersRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/payment/failure': typeof PaymentFailureRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/market/$symbol': typeof AuthenticatedMarketSymbolRoute
  '/wallet/deposit': typeof AuthenticatedWalletDepositRoute
  '/wallet/history': typeof AuthenticatedWalletHistoryRoute
  '/wallet/transfer': typeof AuthenticatedWalletTransferRoute
  '/wallet/withdraw': typeof AuthenticatedWalletWithdrawRoute
  '/wallet': typeof AuthenticatedWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/market': typeof AuthenticatedMarketRouteWithChildren
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRouteWithChildren
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/payment/failure': typeof PaymentFailureRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/_authenticated/market/$symbol': typeof AuthenticatedMarketSymbolRoute
  '/_authenticated/wallet/deposit': typeof AuthenticatedWalletDepositRoute
  '/_authenticated/wallet/history': typeof AuthenticatedWalletHistoryRoute
  '/_authenticated/wallet/transfer': typeof AuthenticatedWalletTransferRoute
  '/_authenticated/wallet/withdraw': typeof AuthenticatedWalletWithdrawRoute
  '/_authenticated/wallet/': typeof AuthenticatedWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-otp'
    | '/admin'
    | '/dashboard'
    | '/market'
    | '/orders'
    | '/portfolio'
    | '/wallet'
    | '/watchlist'
    | '/payment/failure'
    | '/payment/success'
    | '/market/$symbol'
    | '/wallet/deposit'
    | '/wallet/history'
    | '/wallet/transfer'
    | '/wallet/withdraw'
    | '/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-otp'
    | '/admin'
    | '/dashboard'
    | '/market'
    | '/orders'
    | '/portfolio'
    | '/watchlist'
    | '/payment/failure'
    | '/payment/success'
    | '/market/$symbol'
    | '/wallet/deposit'
    | '/wallet/history'
    | '/wallet/transfer'
    | '/wallet/withdraw'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-otp'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/market'
    | '/_authenticated/orders'
    | '/_authenticated/portfolio'
    | '/_authenticated/wallet'
    | '/_authenticated/watchlist'
    | '/payment/failure'
    | '/payment/success'
    | '/_authenticated/market/$symbol'
    | '/_authenticated/wallet/deposit'
    | '/_authenticated/wallet/history'
    | '/_authenticated/wallet/transfer'
    | '/_authenticated/wallet/withdraw'
    | '/_authenticated/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  PaymentFailureRoute: typeof PaymentFailureRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/market': {
      id: '/_authenticated/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/payment/failure': {
      id: '/payment/failure'
      path: '/payment/failure'
      fullPath: '/payment/failure'
      preLoaderRoute: typeof PaymentFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/market/$symbol': {
      id: '/_authenticated/market/$symbol'
      path: '/$symbol'
      fullPath: '/market/$symbol'
      preLoaderRoute: typeof AuthenticatedMarketSymbolRouteImport
      parentRoute: typeof AuthenticatedMarketRoute
    }
    '/_authenticated/wallet/': {
      id: '/_authenticated/wallet/'
      path: '/'
      fullPath: '/wallet/'
      preLoaderRoute: typeof AuthenticatedWalletIndexRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/wallet/deposit': {
      id: '/_authenticated/wallet/deposit'
      path: '/deposit'
      fullPath: '/wallet/deposit'
      preLoaderRoute: typeof AuthenticatedWalletDepositRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/wallet/history': {
      id: '/_authenticated/wallet/history'
      path: '/history'
      fullPath: '/wallet/history'
      preLoaderRoute: typeof AuthenticatedWalletHistoryRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/wallet/transfer': {
      id: '/_authenticated/wallet/transfer'
      path: '/transfer'
      fullPath: '/wallet/transfer'
      preLoaderRoute: typeof AuthenticatedWalletTransferRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/wallet/withdraw': {
      id: '/_authenticated/wallet/withdraw'
      path: '/withdraw'
      fullPath: '/wallet/withdraw'
      preLoaderRoute: typeof AuthenticatedWalletWithdrawRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
  }
}

interface AuthenticatedMarketRouteChildren {
  AuthenticatedMarketSymbolRoute: typeof AuthenticatedMarketSymbolRoute
}

const AuthenticatedMarketRouteChildren: AuthenticatedMarketRouteChildren = {
  AuthenticatedMarketSymbolRoute: AuthenticatedMarketSymbolRoute,
}

const AuthenticatedMarketRouteWithChildren =
  AuthenticatedMarketRoute._addFileChildren(AuthenticatedMarketRouteChildren)

interface AuthenticatedWalletRouteChildren {
  AuthenticatedWalletDepositRoute: typeof AuthenticatedWalletDepositRoute
  AuthenticatedWalletHistoryRoute: typeof AuthenticatedWalletHistoryRoute
  AuthenticatedWalletTransferRoute: typeof AuthenticatedWalletTransferRoute
  AuthenticatedWalletWithdrawRoute: typeof AuthenticatedWalletWithdrawRoute
  AuthenticatedWalletIndexRoute: typeof AuthenticatedWalletIndexRoute
}

const AuthenticatedWalletRouteChildren: AuthenticatedWalletRouteChildren = {
  AuthenticatedWalletDepositRoute: AuthenticatedWalletDepositRoute,
  AuthenticatedWalletHistoryRoute: AuthenticatedWalletHistoryRoute,
  AuthenticatedWalletTransferRoute: AuthenticatedWalletTransferRoute,
  AuthenticatedWalletWithdrawRoute: AuthenticatedWalletWithdrawRoute,
  AuthenticatedWalletIndexRoute: AuthenticatedWalletIndexRoute,
}

const AuthenticatedWalletRouteWithChildren =
  AuthenticatedWalletRoute._addFileChildren(AuthenticatedWalletRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMarketRoute: typeof AuthenticatedMarketRouteWithChildren
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRouteWithChildren
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMarketRoute: AuthenticatedMarketRouteWithChildren,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRouteWithChildren,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  PaymentFailureRoute: PaymentFailureRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
